### ISSUE TITLE
Permashow Drawing toggle-state-indicators are misaligned with respect to the grey-background bars.

### ISSUE THREAD

**Issue by jayblah** [LeagueSharp/LeagueSharp.Common#320]
Please refer to screenshot for visual: https://i.imgur.com/q8qp7VA.png

The TRUE/FALSE toggle-state-indicators do not fit properly within the dimensions of the individual button/bars themselves. You can see they extend past the border, and are also vertically misaligned.

**Comment by SephLeague** [comment]
try going to leaguesharp.common, permashow and press default. what is your screen resolution by the way?

**Comment by jayblah** [comment]
1920x1080

J.R.

**Comment by jayblah** [comment]
Settings are on default, btw.

J.R.

**Comment by jayblah** [comment]
I was wrong, that screen is not default. Seph, here's what default settings
looks like. https://i.imgur.com/IT5Gtd3.png

Same issues with alignment.

J.R.

**Comment by SephLeague** [comment]
Fixed, I think.

**Comment by jayblah** [comment]
Hi bud, thank you for the effort, but it's not fixed. See screenshot. This is with DEFAULT settings, promise.

https://i.imgur.com/AIj4YJO.png

**Comment by SephLeague** [comment]
Ok, will fix tomorrow

**Comment by xKurisu** [comment]
Was something wrong with the old one? the font text and all was fine. :/

**Comment by SephLeague** [comment]
@xKurisu Well, not much has changed except XQX's commit which just made it so it reads font and font size from menu settings. Other than that, its just bug fixes and some minor changes. 

@jayblah The issue has been resolved. Thanks for reporting/testing!
